service: nodejs-lambda-s3

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: "arn:aws:s3:::systemadminJs/*"

functions:
  app:
    handler: handler.handler
    events:
      - httpApi:
          path: /upload
          method: post

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: systemadminJs